query GetFiscalEntities($type: FiscalEntityType, $pagination: PaginationInput) {
  fiscalEntities(fiscalEntityType: $type, pagination: $pagination) {
    items {
      id
      name
      type
      country
      province
      userId
      createdAt
      updatedAt
    }
    total
    skip
    take
    hasMore
  }
}

query GetFiscalEntity($id: ID!) {
  fiscalEntity(id: $id) {
    id
    name
    type
    country
    province
    userId
    createdAt
    updatedAt
  }
}

mutation CreateFiscalEntity($input: FiscalEntityInput!) {
  createFiscalEntity(input: $input) {
    id
    name
    type
    country
    province
    userId
    createdAt
    updatedAt
  }
}

mutation UpdateFiscalEntity($id: ID!, $input: UpdateFiscalEntityInput!) {
  updateFiscalEntity(id: $id, input: $input) {
    id
    name
    type
    country
    province
    userId
    createdAt
    updatedAt
  }
}

mutation DeleteFiscalEntity($id: ID!) {
  deleteFiscalEntity(id: $id)
}
